---
title: "MATH 588"
subtitle: "HW4"
author: "Md Ismail Hossain"
date: "2/23/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE,message=FALSE)
```

\newpage

# Question 1
## a
```{r}
library(Sleuth3)
bb = case1102
sapply(bb, class) # Simplify future typeing by changing names to lower case:
names(bb) = casefold(names(bb)) 
names(bb)

# Make new variables 
bb$logBLratio = log(bb$brain/bb$liver)
bb$logTime = log(bb$time)

# a(1)
library(dplyr)
with(bb, table(sex)) %>% prop.table()

# a(2)
with(bb, table(treatment,days)) %>% prop.table()
```

## b

```{r}
# b

# Plot key variables
with(bb, plot(logBLratio ~ logTime, pch=as.numeric(bb$treat), xlab="Log Time"))
with(bb, table(bb$treat,as.numeric(bb$treat)))
legend("topleft", legend=c("Barrier Disruption","Saline Control"), pch=1:2)
```

## c

```{r}

m0 = lm(logBLratio ~ logTime + treatment, bb)
summary(m0)
```

## d

```{r}
m1 = lm(logBLratio ~ logTime*treatment, bb)
summary(m1)
```

## e

```{r}
plot(m0, which=c(1,1))
plot(m1, which=c(1,1))
```


